// <auto-generated />
namespace B2D3.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Version8 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Version8));
        
        string IMigrationMetadata.Id
        {
            get { return "201706211212012_Version8"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
